services:
  - type: web
    name: fitness-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        value: https://fitness-ebon-nine.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://fitness-ebon-nine.vercel.app
